title: Akawaka Documentation Hub
description: Centralized docs for all Akawaka projects.

url: "https://akawaka.github.io"
baseurl: "/doc"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/slate@v0.2.0

author: "Akawaka Team"
twitter:
  username: akawaka
social:
  name: "Akawaka"
  links:
    - "https://github.com/akawaka"
    - "https://www.akawaka.fr/"

nav_links:
  - title: Home
    url: /
  - title: Opencode
    url: /opencode/

# Plugins - Enhanced for better Markdown processing and cross-linking
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-relative-links      # Enables relative links between markdown files
  - jekyll-optional-front-matter  # Allows markdown files without front matter
  - jekyll-readme-index        # Treats README.md as index files
  - jekyll-default-layout      # Applies default layouts automatically
  - jekyll-titles-from-headings  # Generates page titles from headings

# SEO and Social
logo: /assets/images/akawaka-logo.png
social:
  name: Akawaka
  links:
    - https://github.com/akawaka
    - https://www.akawaka.fr/
    - https://www.linkedin.com/company/akawaka
    - https://twitter.com/akawaka

# Default layouts - Enhanced for automatic processing
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "opencode"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "opencode/**/*.md"
    values:
      layout: "default"
  - scope:
      path: "index"
    values:
      layout: "default"
  # Automatically process all markdown files
  - scope:
      path: "**/*.md"
    values:
      layout: "default"

# Exclude from build
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dist/
  - install.sh
  - .git/
  - .github/
  - README.md

# Include specific files
include:
  - _pages

# Enhanced Kramdown configuration for better Markdown parsing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..4
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

# Collections (if needed for future expansion)
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Site-wide settings
timezone: Europe/Paris
lang: en

# Plugin configurations
relative_links:
  enabled: true
  collections: true

optional_front_matter:
  remove_originals: true

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
