title: Akawaka Documentation Hub
description: Centralized docs for all Akawaka projects.

url: "https://akawaka.github.io"
baseurl: "/doc"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

author: "Akawaka Team"
twitter:
  username: akawaka
social:
  name: "Akawaka"
  links:
    - "https://github.com/akawaka"

nav_links:
  - title: Home
    url: /
  - title: Opencode
    url: /opencode/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata  # ADD THIS for better GitHub integration

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "opencode"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index"
    values:
      layout: "default"

# Exclude from build
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dist/
  - install.sh
  - .git/
  - .github/
  - README.md

# Include specific files
include:
  - _pages

# Enhanced Kramdown configuration for better Markdown parsing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..4
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
